import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFill } from "react-icons/ai";
import spaceX from "../public/spaceX.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Justin Ochoa Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">Justin Ochoa</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="../Justin.Ochoa.pdf"
                  target="_blank"
                  rel="noreferrer"
                >
                  My Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Justin Ochoa
            </h2>
            <h3 className="text-2xl py-2">Front End Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              I attended Ironhack Miami Coding Bootcamp from March 2020 to June
              2020.
              <br />
              Currently a front end developer for Q Link Wireless since February
              2021.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a
              href="https://github.com/justinochoa5792"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillGithub />
            </a>
            <a
              href="https://www.linkedin.com/in/justinochoa5792/"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillLinkedin />
            </a>
          </div>
        </section>
        {/* Section 2 */}
        <section>
          <div className="text-3xl py-1 text-center">Personal Projects</div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10">
            <Image width={200} height={150} src={spaceX} alt="spaceX" />
            <h3 className="text-lg font-mediumpt-8 pb-2">SpaceX Launch App </h3>
            <p className="text-gray-800 py-1">
              Web app that uses React, Node.js, GraphQL and SpaceX API.
            </p>
            <h4 className="py-4 text-teal-600">
              <a
                href="https://murmuring-refuge-43401.herokuapp.com/"
                target="_blank"
                rel="noreferrer"
              >
                Check it out
              </a>
            </h4>
          </div>
        </section>
      </main>
    </div>
  );
}
